### ISSUE TITLE
have_framework isn't available in mkmf in 1.9.2 - cannot build native extensions

### ISSUE THREAD

**Issue by mistydemeo** [nagachika/ruby-coreaudio#1]
When trying to install coreaudio, I received the following error:

```
Building native extensions.  This could take a while...
ERROR:  Error installing coreaudio:
    ERROR: Failed to build gem native extension.

        /Users/mistydemeo/.rvm/rubies/ruby-1.9.2-p290/bin/ruby extconf.rb
*** extconf.rb failed ***

...

extconf.rb:6:in `<main>': undefined method `have_framework' for main:Object (NoMethodError)
```

I was using Ruby 1.9.2p290 installed via RVM on Mac OS X 10.6.8.

It looks like have_framework was added to mkmf recently - it was available when I tried to build on Ruby 1.9.3rc1, but not on 1.9.2.

Since 1.9.3 is coming out soon anyway, this may not be a big problem.
